# -*- coding: utf-8 -*-
"""chromdbPDF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-FHlKGMl9w8QfoCLAGaNia9rNNsqPipx
"""

!pip install pypdf

!pip install sentence-transformers

!pip install chromadb

import os
import time
from pypdf import PdfReader
from sentence_transformers import SentenceTransformer
import chromadb
from chromadb import PersistentClient

pdf_folder_path="/content/data"

def extract_text_from_pdfs(pdf_folder_path):
    documents = {}
    doc_id = 1

    for file_name in os.listdir(pdf_folder_path):
        if file_name.lower().endswith(".pdf"):
            file_path = os.path.join(pdf_folder_path, file_name)
            reader = PdfReader(file_path)

            text = ""
            for page in reader.pages:
                page_text = page.extract_text()
                if page_text:
                    text += page_text + " "

            if text.strip():
                documents[f"doc_{doc_id}"] = text
                doc_id += 1

    return documents

# Load Embedding Model
model = SentenceTransformer("sentence-transformers/all-distilroberta-v1")
embedding_dim = model.get_sentence_embedding_dimension()

print("Embedding dimension:", embedding_dim)

start_time = time.time()
documents = extract_text_from_pdfs(pdf_folder_path)
end_time = time.time()

print(f"Text extraction completed in {end_time - start_time:.2f} seconds")
print(f"Total documents loaded: {len(documents)}")

# Initialize ChromaDB (Modern Persistent Client)
chroma_client = chromadb.PersistentClient(
    path="./chroma_db"     # folder where vectors are stored
)

collection_name = "resume_search"

# Delete old collection if exists
try:
    chroma_client.delete_collection(collection_name)
    print("Old collection deleted")
except:
    pass

# Create new collection
collection = chroma_client.create_collection(
    name=collection_name
)

# Generate Embeddings
doc_ids = list(documents.keys())
doc_texts = list(documents.values())

embeddings=model.encode(
    doc_texts,
    batch_size=32,
    show_progress_bar=True
).tolist()

print("Embedding vector length:", len(embeddings[0]))

# storing embeddings and documents into chromadb Collection

collection.add(
    documents=doc_texts,
    ids=doc_ids,
    embeddings=embeddings
)

# ---------------------------------------------------------
# Queries for performance test
# ---------------------------------------------------------
queries = {
    "Sentence 1": "data engineering resume azure data factory databricks",
    "Sentence 2": "data science machine learning langchain gen ai agentic ai",
    "Sentence 3": "python developer machine learning projects"
}

results_table = []

# ---------------------------------------------------------
# Run Benchmark
# ---------------------------------------------------------
for label, query_text in queries.items():

    print(f"\nRunning {label}...")

    # Embedding timing
    embed_start = time.time()
    query_embedding = model.encode(query_text).tolist()
    embed_end = time.time()

    # ChromaDB search timing
    search_start = time.time()

    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=5
    )

    search_end = time.time()

    embedding_time = embed_end - embed_start
    chroma_time = search_end - search_start
    total_time = search_end - embed_start

    results_table.append({
        "Query": label,
        "Embedding Time": round(embedding_time, 4),
        "ChromaDB Time": round(chroma_time, 4),
        "Total Time": round(total_time, 4)
    })

# ---------------------------------------------------------
# Print Results
# ---------------------------------------------------------
print("\n================ PERFORMANCE COMPARISON ================\n")

print(f"{'Query':<12} | {'Embedding (s)':<14} | {'ChromaDB (s)':<14} | {'Total (s)':<10}")
print("-" * 65)

for row in results_table:
    print(
        f"{row['Query']:<12} | "
        f"{row['Embedding Time']:<14} | "
        f"{row['ChromaDB Time']:<14} | "
        f"{row['Total Time']:<10}"
    )

print("\n=======================================================\n")